spring:
  application:
    name: 'learnMVC'

  datasource:
    url: 'jdbc:postgresql://localhost:5432/learnMVC_db'
    username: 'postgres'
    password: 'my3Pass'

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      dll-auto: update

server:
  port: 8000